openapi: 3.1.1
info:
  title: Eric's Barber API
  version: 1.0.0
  description: API for booking appointments at Eric's Barber Shop
  contact:
    name: Eric's Barber Shop
    email: fahmidhaque-dev@proton.me
    url: https://www.ericsbarbershop.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /appointments:
    get:
      summary: Get all appointments
      responses:
        '200':
          description: A list of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
    post:
      summary: Create a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid input
  /appointments/{id}:
    get:
      summary: Get an appointment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Appointment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '404':
          description: Appointment not found
    put:
      summary: Update an appointment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Appointment updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid input
        '404':
          description: Appointment not found
    delete:
      summary: Delete an appointment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Appointment deleted successfully
        '404':
          description: Appointment not found
  /barbers:
    get:
      summary: Get all barbers
      responses:
        '200':
          description: A list of barbers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Barber'
    post:
      summary: Create a new barber
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Barber'
      responses:
        '201':
          description: Barber created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Barber'
        '400':
          description: Invalid input
  /barbers/{id}:
    get:
      summary: Get a barber by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Barber details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Barber'
        '404':
          description: Barber not found
    put:
      summary: Update a barber by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Barber'
      responses:
        '200':
          description: Barber updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Barber'
        '400':
          description: Invalid input
        '404':
          description: Barber not found
    delete:
      summary: Delete a barber by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Barber deleted successfully
        '404':
          description: Barber not found
          
components:
  schemas:
    Barber:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
      required:
        - name
        - phone
    Appointment:
      type: object
      properties:
        id:
          type: string
        barberId:
          type: string
        customerName:
          type: string
        appointmentTime:
          type: string
          format: date-time
        serviceType:
          type: string
        status:
          type: string
          enum: [scheduled, completed, canceled]